---
- name: Create config directory
  file: path={{ teamcity.data_path }}/config/ owner={{ teamcity.user }} group={{ teamcity.user }} recurse=yes state=directory

- name: Create database settings
  template: src=database.properties.j2 dest={{teamcity.data_path}}/config/database.properties owner={{ teamcity.user }} group={{ teamcity.user }} mode=755

- name: Create server systemd configuration
  template: src=teamcity-server.j2 dest=/etc/systemd/system/teamcity-server.service mode=755
  notify: reload teamcity-server

- name: Create agent systemd configuration
  template: src=teamcity-agent.j2 dest=/etc/systemd/system/teamcity-agent.service mode=755
  notify: reload teamcity-agent
